openapi: 3.0.2
info:
  title: Retrieval Plugin API
  description: A retrieval API for querying and filtering documents based on natural language queries and metadata
  version: 1.0.0
paths:
  /createRecurringTokenTransfer:
    post:
      summary: createRecurringTokenTransfer
      description: Accepts Solana pubkey address for `amount`, `destination`, and `mint` to create a recurring token transfer. Returns a transaction signature
      operationId: create_recurring_token_transfer_tx
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createRecurringTokenTransferRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transactionResponse"
        "500":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - HTTPBearer: []
components:
  schemas:
    createRecurringTokenTransferRequest:
      title: CreateRecurringTokenTransferRequest
      type: object
      properties:
        amount:
          type: string
        destination:
          type: string
        mint:
          type: string
    transactionResponse:
      type: object
      properties:
        linkToSign:
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        message:
          title: Message
          type: string
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer